# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "09341ab55f51f8980ad6dc857de5af64"
name = "juppiter bot"
handle = "juppiter-bot"
application_url = "https://requiring-identical-fort-portal.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "juppiter-app-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://requiring-identical-fort-portal.trycloudflare.com/auth/callback",
  "https://requiring-identical-fort-portal.trycloudflare.com/auth/shopify/callback",
  "https://requiring-identical-fort-portal.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
